Script overhaul
Much simpler
Common library

diff --git a/mount-image b/mount-image
--- a/mount-image
+++ b/mount-image
@@ -36,80 +36,41 @@
 #
 ################################################################################
 
-ifs_original=$IFS # Reset when done
-IFS='
-' # Make sure paths with spaces don't make any trouble when looping
+directory="$(dirname -- "$(readlink -f -- "$0")")"
+. "${directory}/common.sh" || exit $EX_UNKNOWN
 
-PATH='/usr/bin:/bin'
-cmdname=$(basename $0)
-description='ISO Mounter'
-
-mount_dir='/media'
-
-# Exit codes from /usr/include/sysexits.h, as recommended by
-# http://www.faqs.org/docs/abs/HTML/exitcodes.html
-EX_OK=0           # successful termination
-EX_SOFTWARE=70    # internal software error
-EX_CANTCREAT=73   # can't create (user) output file
-
-# Custom errors
-EX_UNKNOWN=1
-
-error()
-{
-    if [ -z "$2" ]
-    then
-        error_code=$EX_UNKNOWN
-    else
-        error_code=$2
-    fi
-    zenity --error --title $description --text $1
-    exit $error_code
-}
-
-warning()
-{
-    zenity --warning --title $description --text $1
-}
-
-for iso_path in $*
+for image_path
 do
-    # Check the file type before continuing
-    if [ -z "$(file -b $iso_path | grep 'ISO 9660\|UDF filesystem')" ]
-    then
-        warning "'${iso_path}' appears not to be an ISO file. Skipping."
-        continue
-    fi
-
-    iso_filename=$(basename $iso_path)
-    iso_mount_path=${mount_dir}/${iso_filename}
+    setup $1 || continue
 
     # Create mount directory
-    if [ ! -d $iso_mount_path ]
+    if [ ! -d "$image_mount_path" ]
     then
-        gksudo --description $description -- mkdir -p $iso_mount_path || \
-            error "Couldn't create mount directory '${iso_mount_path}'." $EX_CANTCREAT
+        gksudo --description "$description" -- \
+        mkdir -p -- "$image_mount_path" || \
+            error "Couldn't create mount directory '${image_mount_path}'." \
+            $EX_CANTCREAT
     fi
 
     # Skip if the file is already mounted
-    if [ $(ls -A $iso_mount_path | wc -l) -ne 0 ]
+    if [ -n "$(ls -A -- "$image_mount_path")" ]
     then
-        warning "'${iso_path}' is already mounted at '${iso_mount_path}'."
+        warning "'${image_path}' is already mounted at '${image_mount_path}'."
         continue
     fi
 
     # Mount file
-    gksudo --description $description -- mount -o loop -t iso9660 $iso_path $iso_mount_path || \
-        error "Couldn't mount ISO file '${iso_path}' at '${iso_mount_path}'." $EX_SOFTWARE
+    gksudo --description "$description" -- \
+    mount -o loop -t iso9660 "$image_path" "$image_mount_path" || \
+        error "Couldn't mount '${image_path}' at '${image_mount_path}'." \
+        $EX_SOFTWARE
 
     # Create shortcut from the ISO location
-    link_path=$(dirname $iso_path)/${iso_filename%.*}
-    if [ ! -e $link_path ]
+    if [ ! -e "$link_path" ]
     then
-        gksudo --description $description -- ln -s $iso_mount_path $link_path || \
-            error "Couldn't create symbolic link '${link_path}'." $EX_CANTCREAT
+        gksudo --description "$description" -- \
+        ln -s "$image_mount_path" "$link_path" || \
+            error "Couldn't create symbolic link '${link_path}'." \
+            $EX_CANTCREAT
     fi
 done
-
-# Cleanup
-IFS=$ifs_original
diff --git a/umount-image b/umount-image
--- a/umount-image
+++ b/umount-image
@@ -27,79 +27,38 @@
 #
 ################################################################################
 
-ifs_original="$IFS" # Reset when done
-IFS='
-' # Make sure paths with spaces don't make any trouble when looping
+directory="$(dirname -- "$(readlink -f -- "$0")")"
+. "${directory}/common.sh" || exit $EX_UNKNOWN
 
-PATH='/usr/bin:/bin'
-cmdname=$(basename $0)
-description='ISO Mounter'
-
-mount_dir='/media'
-
-# Exit codes from /usr/include/sysexits.h, as recommended by
-# http://www.faqs.org/docs/abs/HTML/exitcodes.html
-EX_OK=0           # successful termination
-EX_OSERR=71       # system error (e.g., can't fork)
-
-# Custom errors
-EX_UNKNOWN=1
-
-error()
-{
-    if [ -z "$2" ]
-    then
-        error_code=$EX_UNKNOWN
-    else
-        error_code=$2
-    fi
-    zenity --error --title "$description" --text "$1"
-    exit $error_code
-}
-
-warning()
-{
-    zenity --warning --title "$description" --text "$1"
-}
-
-for iso_path in $*
+for image_path
 do
-    # Check the file type before continuing
-    if [ -z "$(file -b $iso_path | grep 'ISO 9660\|UDF filesystem')" ]
-    then
-        warning "'${iso_path}' appears not to be an ISO file. Skipping."
-        continue
-    fi
+    setup $1 || continue
 
-    iso_filename=$(basename $iso_path)
- 
     # Remove shortcut
-    link_path=$(dirname $iso_path)/${iso_filename%.*}
-    if [ -L $link_path ]
+    if [ -L "$link_path" ]
     then
-        gksudo --description $description -- rm $link_path || \
+        gksudo --description "$description" -- \
+        rm -- "$link_path" || \
             warning "Couldn't remove symbolic link '${link_path}'."
     fi
 
     # Abort if the file is already unmounted
-    iso_mount_path=$mount_dir/${iso_filename}
-    if [ ! -d $iso_mount_path ]
+    if [ ! -d "$image_mount_path" ]
     then
-        warning "'${iso_path}' is not mounted."
+        warning "'${image_path}' is not mounted."
         continue
     fi
 
     # Unmount file
-    gksudo --description $description -- umount $iso_mount_path || \
-        error "Couldn't unmount '${iso_mount_path}'." $EX_OSERR
+    gksudo --description "$description" -- \
+    umount -- "$image_mount_path" || \
+        error "Couldn't unmount '${image_mount_path}'." $EX_OSERR
 
     # Remove mount directory
-    if [ -d $iso_mount_path ]
+    if [ -d "$image_mount_path" ]
     then
-        gksudo --description $description -- rmdir $iso_mount_path || \
-            warning "Couldn't remove mount directory '${iso_mount_path}'."
+        gksudo --description "$description" -- \
+        rmdir -- "$image_mount_path" || \
+            warning "Couldn't remove mount directory '${image_mount_path}'."
     fi
 done
-
-# Cleanup
-IFS=$ifs_original
